"""empty message

Revision ID: 17cebadd46b3
Revises: e6dd4ae0d67d
Create Date: 2021-04-23 12:03:58.725461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cebadd46b3'
down_revision = 'e6dd4ae0d67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=100), nullable=True))
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
