"""empty message

Revision ID: 518c16b70138
Revises: 
Create Date: 2021-04-09 08:28:18.842124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518c16b70138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbluser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('confirmations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbluser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbladdress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_first_name', sa.String(length=80), nullable=False),
    sa.Column('user_last_name', sa.String(length=80), nullable=False),
    sa.Column('user_phone_number', sa.String(length=14), nullable=False),
    sa.Column('user_landline', sa.String(length=14), nullable=False),
    sa.Column('user_image_path', sa.String(length=50), nullable=False),
    sa.Column('account_status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbluser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_image_path'),
    sa.UniqueConstraint('user_landline'),
    sa.UniqueConstraint('user_phone_number')
    )
    op.create_table('tblorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('order_status', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbluser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblpayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tblorders.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['tbluser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblpayments')
    op.drop_table('tblorders')
    op.drop_table('tbladdress')
    op.drop_table('items')
    op.drop_table('confirmations')
    op.drop_table('tbluser')
    op.drop_table('stores')
    # ### end Alembic commands ###
