"""Added isAdmin column in the user table

Revision ID: 58bb647888f4
Revises: 518c16b70138
Create Date: 2021-04-09 11:10:54.545792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bb647888f4'
down_revision = '518c16b70138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbluser', sa.Column('isAdmin', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbluser', 'isAdmin')
    # ### end Alembic commands ###
